# Generated by Django 3.1.7 on 2021-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210316_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
