# Generated by Django 3.1.7 on 2021-03-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userprofileinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.TextField(blank=True, default='Edit your information', max_length=1000),
        ),
    ]
