# Generated by Django 3.1.7 on 2021-03-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210317_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(default='default2.jpg', upload_to='review_pics'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
