# Generated by Django 3.1.7 on 2021-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210319_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(default='default2.jpg', upload_to='review_pics'),
        ),
    ]
