# Generated by Django 3.1.7 on 2021-03-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
    ]
